/**
 * CyberGuard regression harness for the Digital Impersonation section.
 *
 * Run with:  node test_sender_logic.mjs
 *
 * Everything is read from the real sources (no DOM required):
 *
 *   1. sender rules in script.js — the SENDER field accepts an email
 *      address or a phone number only
 *   2. organisation profile rules in script.js — sample data is derived
 *      from Organisation Settings (name + email domain)
 *   3. the demo dataset generated by script.js for the default
 *      organisation equals test_impersonation_local.py's DEMO_MESSAGES
 *   4. the same rows appear in cyberguard_impersonation_messages.csv
 *   5. every sample row claims and names the configured organisation,
 *      and no unrelated third-party brands appear in the sample data
 */
import { readFileSync } from "node:fs";

const scriptSource = readFileSync("script.js", "utf8");
const pythonSource = readFileSync("test_impersonation_local.py", "utf8");
const csvSource = readFileSync("cyberguard_impersonation_messages.csv", "utf8");

const failures = [];
const fail = message => failures.push(message);

function canonical(value) {
    if (Array.isArray(value)) return value.map(canonical);
    if (value && typeof value === "object") {
        return Object.keys(value).sort().reduce((acc, key) => {
            acc[key] = canonical(value[key]);
            return acc;
        }, {});
    }
    return value;
}

const same = (left, right) =>
    JSON.stringify(canonical(left)) === JSON.stringify(canonical(right));

/* ============================================================
   1. SENDER RULES (script.js)
   ============================================================ */

const senderStart = scriptSource.indexOf("const IMPERSONATION_EMAIL_PATTERN");
const senderEnd = scriptSource.indexOf("function initializeDigitalImpersonation");

if (senderStart < 0 || senderEnd < 0 || senderEnd < senderStart) {
    console.error("could not locate sender helpers in script.js");
    process.exit(1);
}

const senderApi = new Function(
    `${scriptSource.slice(senderStart, senderEnd)}
    return { classifyImpersonationSender, normaliseImpersonationPhone, buildImpersonationMessage, buildImpersonationDemoMessages };
`
)();

const { classifyImpersonationSender, normaliseImpersonationPhone, buildImpersonationMessage, buildImpersonationDemoMessages } = senderApi;

const expectKind = (input, expected) => {
    const actual = classifyImpersonationSender(input);
    if (actual !== expected) fail(`classify(${JSON.stringify(input)}) => ${actual}, expected ${expected}`);
};

// Accepted inputs
expectKind("alerts@secure-login.xyz", "email");
expectKind("  anil.verma@acme-corp.com ", "email");
expectKind("+91 98765 43210", "phone");
expectKind("+911234567890", "phone");
expectKind("98765 43210", "phone");
expectKind("(022) 4001-2345", "phone");

// Rejected inputs (names, malformed values, too-short numbers)
expectKind("", null);
expectKind("   ", null);
expectKind("IT Service Desk", null);
expectKind("Unknown", null);
expectKind("HR Admin", null);
expectKind("foo@bar", null);
expectKind("name@@company.com", null);
expectKind("12345", null);
expectKind("call me maybe", null);

// Phone normalisation groups separators for campaign clustering
if (normaliseImpersonationPhone("+91 98765 43210") !== "+919876543210") {
    fail(`normalise(+91 98765 43210) => ${normaliseImpersonationPhone("+91 98765 43210")}`);
}
if (normaliseImpersonationPhone("(022) 4001-2345") !== "02240012345") {
    fail(`normalise((022) 4001-2345) => ${normaliseImpersonationPhone("(022) 4001-2345")}`);
}

// Payload shape
const emailMessage = buildImpersonationMessage("alerts@acme-corp.com", "Your account will be suspended today.");
if (!emailMessage || emailMessage.channel !== "email") fail("email sender must produce channel=email");
if (emailMessage && emailMessage.sender_domain !== "acme-corp.com") fail(`email sender_domain => ${emailMessage?.sender_domain}`);

const phoneMessage = buildImpersonationMessage("+91 98765 43210", "URGENT notice: your account will be frozen.");
if (!phoneMessage || phoneMessage.channel !== "sms") fail("phone sender must produce channel=sms");
if (phoneMessage && phoneMessage.sender_domain !== "+919876543210") fail(`phone sender_domain => ${phoneMessage?.sender_domain}`);

if (buildImpersonationMessage("IT Service Desk", "hello") !== null) {
    fail("a display-name sender must not build a message");
}
if (buildImpersonationMessage("", "hello") !== null) {
    fail("an empty sender must not build a message");
}

/* ============================================================
   2. ORGANISATION PROFILE RULES (script.js)
   ============================================================ */

const orgStart = scriptSource.indexOf("function organisationSlug");
const orgEnd = scriptSource.indexOf("function initializeOrganisationSettings");

if (orgStart < 0 || orgEnd < 0 || orgEnd < orgStart) {
    console.error("could not locate organisation helpers in script.js");
    process.exit(1);
}

const orgBlock = scriptSource.slice(orgStart, orgEnd);

const profileFor = seed => new Function(
    `const state = ${JSON.stringify(seed)}; ${orgBlock}
    return getOrganisationProfile();
`)();

const profileChecks = [
    [{ organisation: "Acme Corporation", organisationDomain: "acme-corp.com" }, { name: "Acme Corporation", domain: "acme-corp.com" }],
    [{ organisation: "Zulu Trading", organisationDomain: "zulu.co.za" }, { name: "Zulu Trading", domain: "zulu.co.za" }],
    [{ organisation: "Zulu Trading", organisationDomain: "" }, { name: "Zulu Trading", domain: "zulu-trading.com" }],
    [{ organisation: "Zulu Trading", organisationDomain: "https://Acme-Corp.com/" }, { name: "Zulu Trading", domain: "acme-corp.com" }],
    [{ organisation: "Zulu Trading", organisationDomain: "not a domain" }, { name: "Zulu Trading", domain: "zulu-trading.com" }],
    [{ organisation: "", organisationDomain: "" }, { name: "Acme Corporation", domain: "acme-corporation.com" }]
];

profileChecks.forEach(([seed, expected]) => {
    const actual = profileFor(seed);
    if (!same(actual, expected)) {
        fail(`getOrganisationProfile(${JSON.stringify(seed)}) => ${JSON.stringify(actual)}, expected ${JSON.stringify(expected)}`);
    }
});

// Out-of-the-box defaults drive the shipped sample data
const stateBlock = scriptSource.slice(
    scriptSource.indexOf("const state = {"),
    scriptSource.indexOf("/* DOM HELPERS")
);

const defaultName = (stateBlock.match(/organisation:\s*"([^"]+)"/) || [])[1];
const defaultDomain = (stateBlock.match(/organisationDomain:\s*"([^"]+)"/) || [])[1];

if (defaultName !== "Acme Corporation" || defaultDomain !== "acme-corp.com") {
    fail(`unexpected organisation defaults in script.js: ${defaultName} / ${defaultDomain}`);
}

const DEFAULT_ORG = { name: defaultName, domain: defaultDomain };

/* ============================================================
   3. DEMO DATASET vs PYTHON PAYLOAD
   ============================================================ */

const demo = buildImpersonationDemoMessages(DEFAULT_ORG);

if (!Array.isArray(demo) || demo.length !== 6) {
    fail(`demo should hold 6 messages, got ${Array.isArray(demo) ? demo.length : typeof demo}`);
}

const pythonStart = pythonSource.indexOf("DEMO_MESSAGES = [");

if (pythonStart < 0) {
    fail("could not locate DEMO_MESSAGES in test_impersonation_local.py");
} else {
    const bodyStart = pythonStart + "DEMO_MESSAGES = [".length;
    const bodyEnd = pythonSource.indexOf("\n]", bodyStart);
    const pythonPayload = new Function(
        `return [${pythonSource.slice(bodyStart, bodyEnd)}]`
    )();

    if (!same(demo, pythonPayload)) {
        fail("script.js demo dataset and test_impersonation_local.py DEMO_MESSAGES have drifted apart");
    }
}

/* ============================================================
   4. DEMO DATASET vs SAMPLE CSV
   ============================================================ */

function parseCsv(source) {
    const rows = [];
    let row = [];
    let cell = "";
    let quoted = false;
    for (let i = 0; i < source.length; i++) {
        const ch = source[i];
        const next = source[i + 1];
        if (ch === '"' && quoted && next === '"') { cell += '"'; i++; continue; }
        if (ch === '"') { quoted = !quoted; continue; }
        if (ch === "," && !quoted) { row.push(cell); cell = ""; continue; }
        if ((ch === "\n" || ch === "\r") && !quoted) {
            if (ch === "\r" && next === "\n") i++;
            row.push(cell); cell = "";
            if (row.some(value => value !== "")) rows.push(row);
            row = [];
            continue;
        }
        cell += ch;
    }
    if (cell || row.length) { row.push(cell); rows.push(row); }
    return rows;
}

const csvRowsRaw = parseCsv(csvSource);
const csvHeader = csvRowsRaw[0] || [];
const expectedColumns = ["timestamp", "message_id", "channel", "sender_name", "sender_domain", "claimed_identity", "claimed_role", "claimed_organisation", "message_text", "context", "expected_label", "expected_attack_category"];

if (!expectedColumns.every(column => csvHeader.includes(column))) {
    fail(`CSV is missing required evaluation columns: ${csvHeader.join(",")}`);
} else {
    const csvRows = csvRowsRaw.slice(1).map(cells =>
        csvHeader.reduce((row, key, index) => { row[key] = cells[index] ?? ""; return row; }, {})
    );

    if (csvRows.length < 120) fail(`expected at least 120 evaluation messages, got ${csvRows.length}`);

    const csvIds = new Set(csvRows.map(row => String(row.message_id || "")));
    demo.forEach(row => {
        if (!csvIds.has(String(row.message_id))) {
            fail(`demo message ${row.message_id} is missing from the expanded evaluation CSV`);
        }
    });
    const invalidLabels = csvRows.filter(row => !["malicious", "borderline", "benign"].includes(row.expected_label));
    if (invalidLabels.length) fail(`evaluation CSV contains ${invalidLabels.length} rows with invalid expected_label values`);
}

/* ============================================================
   5. ORGANISATION-SPECIFIC SAMPLE DATA
   ============================================================ */

const org = DEFAULT_ORG.name;

demo.forEach(message => {
    const kind = classifyImpersonationSender(message.sender_name);
    if (!kind) fail(`demo sender "${message.sender_name}" is not an email or phone number`);
    else if (kind === "email" && message.channel !== "email") fail(`demo ${message.message_id} email sender with channel ${message.channel}`);
    else if (kind === "phone" && message.channel !== "sms") fail(`demo ${message.message_id} phone sender with channel ${message.channel}`);

    if (message.claimed_organisation !== org) {
        fail(`demo ${message.message_id} claims "${message.claimed_organisation}" instead of ${org}`);
    }
    if (!String(message.context || "").includes(org)) {
        fail(`demo ${message.message_id} context does not name the organisation`);
    }
    if (!String(message.message_text || "").includes(org)) {
        fail(`demo ${message.message_id} message text does not name the organisation`);
    }
    if (kind === "email" && !String(message.sender_domain).includes(".")) {
        fail(`demo ${message.message_id} missing sending domain`);
    }
});

// The sample data must describe this organisation, not unrelated brands
const unrelatedBrands = [
    "delhi police", "state bank", "sbi-", "income tax", "university",
    "examination", "hall ticket", "hdfc", "icici", "courier"
];

const serialised = JSON.stringify(demo).toLowerCase();

unrelatedBrands.forEach(brand => {
    if (serialised.includes(brand)) {
        fail(`sample data still references an unrelated brand: "${brand}"`);
    }
});

/* ============================================================ */

if (failures.length) {
    console.log("FAILED CHECKS:");
    failures.forEach(item => console.log(" -", item));
    process.exit(1);
}

console.log("SENDER + ORGANISATION DATA CHECKS PASSED");
